############# English navigation ##############

# main menu
[[main]]
name = "Principal"
url = ""
weight = 1

[[main]]
name = "Nosotros"
url = "about/"
weight = 2

[[main]]
name = "Servicios"
url = "services/"
weight = 3

[[main]]
name = "Como funciona"
url = "how-it-works/"
weight = 4

[[main]]
name = "Cotizaci칩n"
url = "get-a-quote/"
weight = 5

[[main]]
name = "Cont치ctanos"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "Nosotros"
url = "about/"
weight = 1

[[footer]]
name = "Como funciona"
url = "how-it-works/"
weight = 2

[[footer]]
name = "Cotizaci칩n"
url = "get-a-quote/"
weight = 3

[[footer]]
name = "Cont치ctanos"
url = "contact/"
weight = 4